@startuml
title Seq-LongTermCare-181010-1
scale 800 width
actor 請領資格者 as Alice #blue
actor 家庭照顧者 as Bob #red
participant 照管中心或A as CM
participant 長照服務X as COA #yellow
participant 長照服務Y as COB #green
participant 縣市政府 as GOV
participant  長照特種基金 as FUND
actor 吸菸者 as SMOKER #black
autonumber 100
note over Alice, GOV : 長期照顧給付及支付基準(1071101公告版)
note over Alice, CM : 第一節 給付
Alice -> CM : 需求評估
CM -> CM : 長照需要等級
CM -> Alice : 個人額度\n - 照顧及專業服務\n - 交通接送服務\n - 輔具服務及居家無障礙環境改善服務
CM -> Bob : 喘息服務額度
CM -> Alice : 案家可支付自費額度雙方合意簽名
CM -> CM : 核備照顧計畫
note over Alice, CM #red : 異動需重新核定 104-105
note over CM, GOV : 第二節 支付
autonumber 200
CM -> CM : 服務代碼配對
CM -> COA : 病人資料派案
COA -> Alice : 事前準備、實際服務、事後善後及紀錄
Alice -> COA : 自費$
CM -> COB : 照顧者資料派案
COB -> Bob : 事前準備、實際服務、事後善後及紀錄
Bob -> COB : 自費$
note over COA, GOV : 金流$ 每月10日前申報
COA -> GOV : 領款收據、服務費用總表
GOV -> COA : 75日內全額$
FUND ->GOV : 支付$
SMOKER -> FUND : 107年五個月撥入120億元\n菸稅110億元佔九成。
@enduml